// Generated by ReScript, PLEASE EDIT WITH CARE


var Obj = {};

var Pervasives = {};

var $$String = {};

var $$Promise = {};

var Internal = {};

var Undefined = {};

var Js = {
  $$Promise: $$Promise,
  Internal: Internal,
  Undefined: Undefined
};

export {
  Obj ,
  Pervasives ,
  $$String ,
  Js ,
}
/* No side effect */
